name: Validate Builds

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  build_ubuntu:
    runs-on: ubuntu-18.04

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libbsd-dev gettext autopoint autoconf bison libtool pkg-config openjdk-8-jdk libmicrohttpd-dev liburcu-dev libyaml-dev liblz4-dev curl python3-setuptools
        sudo apt-get install libmongoc-1.0-0 libbson-1.0-0 libssl-dev libsasl2-dev
        python3 -m pip install --user setuptools_rust wheel
        python3 -m pip install --user poetry
        python -m pip install --user scons

    - uses: actions/checkout@v2
      with:
        repository: hse-project/hse
        ref: master
        path: hse

    - name: Build and install hse
      run: |
        cd hse
        poetry install
        poetry run meson builddir -Dycsb=true -Dinstall-tools=true -Dinstall-configs=true
        poetry run meson install -C builddir --destdir="${{ runner.temp }}/hse"

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: hse-build-artifact
        path: hse/builddir/meson-logs/

    - uses: actions/checkout@v2

    - name: Build YCSB
      run: |
        mvn install:install-file -Dfile=${{ runner.temp }}/hse/opt/hse/lib/x86_64-linux-gnu/hsejni.jar -DgroupId=test.org.hse -DartifactId=hse -Dversion=0.0 -Dpackaging=jar
        mvn -pl hse -am clean package

  checkoss:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: check for license
      run: |
        hse/checkoss
